services:
  - type: web
    name: latexfiles
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn kursova.wsgi"
    branch: master
    autoDeploy: true
    plan: free